### PR TITLE
Add Documentation for using the config

### PR DESCRIPTION
**Pull request by swashata**
The purpose of this is to add documentation which is beginner friendly to setup and use ESLint and
`eslint-config-wordpress` for projects.

- [x] Add CLI documentation: Use ESLint from CLI.
- [x] Add VSCode documentation: Use VSCode with `eslint-config-wordpress` and auto fix.
- [x] Add `README.md` in `docs` directory to provide TOC.

/cc @ntwb

### CODE REVIEW

**Comment by swashata** [comment]
@ntwb Please review and let me know if the folder structure is the right way to go. I will change things if needed.

**Comment by swashata** [comment]
@ntwb I am done with the docs. Please review.

**Comment by ntwb** [comment]
Apologies for the delay in reviewing this, I'll get stuck into it soon, there is much more here than I was expecting :)

**Comment by swashata** [comment]
@ntwb no issues at all... I am just investing my company time for three weeks of OSS stuff :) My goal is to learn new ES6, React and WordPress Gutenberg. I am happy to help anywhere I can.

**Review by ntwb — APPROVED** [review]

**Comment by ntwb** [comment]
Thanks a bunch @swashata, I decided to merge this as is, there are a couple of minor tweaks but it will be easier for both of us to merge it as is and iterate from there

Thanks 😄

**Comment by swashata** [comment]
Great. Thank you. Do let me know if you need me to edit something.

**Pull request merged**
